[project]
name = "pydict"
version = "0.1.0"
description = "A wrapper for the Oxford Dictionary API"
dependencies =["requests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"